owner: mue
repo: status

sites:
  - name: Website
    url: https://muetab.com
  - name: API
    url: https://api.muetab.com
  - name: CDN (Cloudinary)
    url: https://res.cloudinary.com/mue/image/upload/photos/old/d7eb7a574e11fc43.jpg
  - name: Marketplace
    url: https://marketplace.muetab.com
  - name: Blog
    url: https://blog.muetab.com
  - name: Proxy
    url: https://proxy.muetab.com

status-website:
  cname: status.muetab.com
  logoUrl: https://avatars3.githubusercontent.com/u/58658585?s=200
  name: Mue Status
  introTitle: "Welcome to our statuspage!"
  introMessage: For support, please contact hello@muetab.com or our Twitter (@getmue).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
