owner: mue
repo: status
user-agent: mue

sites:
  - name: Website
    url: https://muetab.com
    icon: https://muetab.com/favicon.ico
  - name: API
    url: https://api.muetab.com
    icon: https://muetab.com/favicon.ico
  - name: CDN
    url: https://cdn.muetab.com/health.txt
    icon: https://assets-global.website-files.com/602eda09fc78afc76e9706b6/607db1d3d1a195db98b50743_storj-favicon-32.png
  - name: Marketplace
    url: https://marketplace.muetab.com
    icon: https://muetab.com/favicon.ico
  - name: Blog
    url: https://blog.muetab.com
    icon: https://muetab.com/favicon.ico
  - name: Proxy
    url: https://proxy.muetab.com
    icon: https://muetab.com/favicon.ico
  - name: Docs
    url: https://docs.muetab.com
    icon: https://muetab.com/favicon.ico

status-website:
  theme: custom
  cname: status.muetab.com
  logoUrl: https://avatars3.githubusercontent.com/u/58658585?s=200
  favicon: https://muetab.com/favicon.ico
  name: Mue Status
  introTitle: "Welcome to our status page!"
  introMessage: For support, please contact hello@muetab.com or our Twitter (@getmue).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
