owner: mue
repo: status

sites:
  - name: Website
    url: https://muetab.com
  - name: API
    url: https://api.muetab.com
  - name: CDN
    url: https://cdn.derpyenterprises.org/mue/mue_verified.svg
  - name: Marketplace
    url: https://marketplace.muetab.com
  - name: Blog
    url: https://blog.muetab.com
  - name: Unsplash Proxy
    url: https://unsplash.muetab.com

status-website:
  cname: status.muetab.com
  logoUrl: https://avatars3.githubusercontent.com/u/58658585?s=200&v=4
  name: Mue Status
  introTitle: "Welcome to our statuspage!"
  introMessage: For support, please contact hello@muetab.com or our Twitter (@getmue).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
